env:
  browser: true
  es2021: true
  node: true
extends: 
  - airbnb-base
  - plugin:jest/recommended
overrides:
  - files:
      - '**/*.test.js'
      - '**/*.spec.js'
    env:
      jest: true
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: 
  no-console: 0
  import/extensions:
    - error
    - ignorePackages
    - js: always
