name: Node CI

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'npm'
      - name: Install dependencies
        run: make install
      - name: Lint code
        run: make lint
